from flask import Flask, request, jsonify, render_template, send_file
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
import tempfile
import joblib
import pandas as pd
import os
import mysql.connector

app = Flask(
    __name__,
    template_folder="../templates",
    static_folder="../static"
)

# ==========================
# Load ML Model
# ==========================
model_path = os.path.join(
    os.path.dirname(__file__),
    "..",
    "models",
    "house_price_model.pkl"
)

model = joblib.load(model_path)

# ==========================
# MySQL Connection
# ==========================
db = mysql.connector.connect(
    host="localhost",
    user="root",
    password="rama750200",
    database="house_price_db"
)

cursor = db.cursor()

# ==========================
# Home Page
# ==========================
@app.route("/")
def home():
    return render_template("index.html")


# ==========================
# Prediction API
# ==========================
@app.route("/predict", methods=["POST"])
def predict():

    data = request.json

    values = [[
        data["bedrooms"],
        data["bathrooms"],
        data["sqft_living"],
        data["sqft_lot"],
        data["floors"],
        data["waterfront"],
        data["view"],
        data["condition"],
        data["sqft_above"],
        data["sqft_basement"],
        data["yr_built"],
        data["yr_renovated"]
    ]]

    columns = [
        "bedrooms",
        "bathrooms",
        "sqft_living",
        "sqft_lot",
        "floors",
        "waterfront",
        "view",
        "condition",
        "sqft_above",
        "sqft_basement",
        "yr_built",
        "yr_renovated"
    ]

    df = pd.DataFrame(values, columns=columns)

    prediction = model.predict(df)[0]

    # Save prediction in MySQL
    sql = """
    INSERT INTO prediction_history(
        bedrooms,
        bathrooms,
        sqft_living,
        sqft_lot,
        floors,
        waterfront,
        view,
        `condition`,
        sqft_above,
        sqft_basement,
        yr_built,
        yr_renovated,
        predicted_price
    )
    VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """

    record = (
        data["bedrooms"],
        data["bathrooms"],
        data["sqft_living"],
        data["sqft_lot"],
        data["floors"],
        data["waterfront"],
        data["view"],
        data["condition"],
        data["sqft_above"],
        data["sqft_basement"],
        data["yr_built"],
        data["yr_renovated"],
        float(prediction)
    )

    cursor.execute(sql, record)
    db.commit()

    return jsonify({
        "Predicted Price": float(prediction)
    })


# ==========================
# Download PDF
# ==========================
@app.route("/download_report", methods=["POST"])
def download_report():

    data = request.json

    temp_file = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".pdf"
    )

    doc = SimpleDocTemplate(temp_file.name)

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph(
            "<b><font size=18>House Price Prediction Report</font></b>",
            styles["Title"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            f"<b>Predicted Price:</b> ₹ {data['predicted_price']:,.2f}",
            styles["BodyText"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph("<b>Property Details</b>", styles["Heading2"])
    )

    story.append(
        Paragraph(
            f"Bedrooms : {data['bedrooms']}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"Bathrooms : {data['bathrooms']}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"Living Area : {data['sqft_living']} sqft",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"Lot Area : {data['sqft_lot']} sqft",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"Floors : {data['floors']}",
            styles["BodyText"]
        )
    )

    story.append(
        Paragraph(
            f"Year Built : {data['yr_built']}",
            styles["BodyText"]
        )
    )

    story.append(Paragraph("<br/>", styles["Normal"]))

    story.append(
        Paragraph(
            "Generated by House Price Prediction System",
            styles["Italic"]
        )
    )

    doc.build(story)

    return send_file(
        temp_file.name,
        as_attachment=True,
        download_name="House_Price_Prediction_Report.pdf"
    )


# ==========================
# Run Flask
# ==========================

@app.route("/history")
def history():

    cursor.execute("SELECT * FROM prediction_history ORDER BY id DESC")

    rows = cursor.fetchall()

    return render_template("history.html", rows=rows)

@app.route("/dashboard")
def dashboard():

    cursor.execute("SELECT COUNT(*) FROM prediction_history")
    total = cursor.fetchone()[0]

    cursor.execute("SELECT AVG(predicted_price) FROM prediction_history")
    avg_price = cursor.fetchone()[0] or 0

    cursor.execute("SELECT MAX(predicted_price) FROM prediction_history")
    max_price = cursor.fetchone()[0] or 0

    cursor.execute("SELECT MIN(predicted_price) FROM prediction_history")
    min_price = cursor.fetchone()[0] or 0

    cursor.execute("SELECT id,predicted_price FROM prediction_history ORDER BY id")

    rows = cursor.fetchall()

    labels = [row[0] for row in rows]
    prices = [float(row[1]) for row in rows]

    return render_template(
        "dashboard.html",
        total=total,
        avg_price=avg_price,
        max_price=max_price,
        min_price=min_price,
        labels=labels,
        prices=prices
    )

if __name__ == "__main__":
    app.run(debug=True)